// <auto-generated />
using Campeonato.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Campeonato.Infra.Data.Migrations
{
    [DbContext(typeof(CampeonatoDbContext))]
    partial class CampeonatoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Campeonato.Domain.Entidade.CampeonatoSydyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CampeonatoSydy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Sydy Championship"
                        });
                });

            modelBuilder.Entity("Campeonato.Domain.Entidade.ParticipanteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("TimeId");

                    b.ToTable("Participante");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampeonatoId = 1,
                            Pontuacao = 0,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CampeonatoId = 1,
                            Pontuacao = 0,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CampeonatoId = 1,
                            Pontuacao = 0,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CampeonatoId = 1,
                            Pontuacao = 0,
                            TimeId = 4
                        });
                });

            modelBuilder.Entity("Campeonato.Domain.Entidade.PartidaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<int>("GolTimeCasa")
                        .HasColumnType("int");

                    b.Property<int>("GolTimeVisitante")
                        .HasColumnType("int");

                    b.Property<int>("TimeCasaId")
                        .HasColumnType("int");

                    b.Property<int>("TimeVisitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("Partida");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampeonatoId = 1,
                            GolTimeCasa = 6,
                            GolTimeVisitante = 5,
                            TimeCasaId = 1,
                            TimeVisitanteId = 2
                        },
                        new
                        {
                            Id = 2,
                            CampeonatoId = 1,
                            GolTimeCasa = 8,
                            GolTimeVisitante = 5,
                            TimeCasaId = 1,
                            TimeVisitanteId = 3
                        },
                        new
                        {
                            Id = 3,
                            CampeonatoId = 1,
                            GolTimeCasa = 5,
                            GolTimeVisitante = 3,
                            TimeCasaId = 1,
                            TimeVisitanteId = 4
                        },
                        new
                        {
                            Id = 4,
                            CampeonatoId = 1,
                            GolTimeCasa = 2,
                            GolTimeVisitante = 8,
                            TimeCasaId = 2,
                            TimeVisitanteId = 3
                        },
                        new
                        {
                            Id = 5,
                            CampeonatoId = 1,
                            GolTimeCasa = 9,
                            GolTimeVisitante = 0,
                            TimeCasaId = 2,
                            TimeVisitanteId = 4
                        },
                        new
                        {
                            Id = 6,
                            CampeonatoId = 1,
                            GolTimeCasa = 9,
                            GolTimeVisitante = 2,
                            TimeCasaId = 3,
                            TimeVisitanteId = 4
                        });
                });

            modelBuilder.Entity("Campeonato.Domain.Entidade.TimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Time");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Sydy Novo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Concorrente"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Visitante"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Time Flopado"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Time Hypado"
                        });
                });

            modelBuilder.Entity("Campeonato.Domain.Entidade.ParticipanteEntity", b =>
                {
                    b.HasOne("Campeonato.Domain.Entidade.CampeonatoSydyEntity", "Campeonato")
                        .WithMany("Participantes")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campeonato.Domain.Entidade.TimeEntity", "Time")
                        .WithMany("Participantes")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campeonato.Domain.Entidade.PartidaEntity", b =>
                {
                    b.HasOne("Campeonato.Domain.Entidade.CampeonatoSydyEntity", "Campeonato")
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campeonato.Domain.Entidade.TimeEntity", "TimeCasa")
                        .WithMany("PartidasCasa")
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Campeonato.Domain.Entidade.TimeEntity", "TimeVisitante")
                        .WithMany("PartidasVisitante")
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
